### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by pauldraper** [izuzak/github_issue_stats#16]
I have been waiting over ten minutes for `github_issue_stats history -i2m -n24  -sangular/angular` to complete.

Any way to make this faster?

**Comment by izuzak** [comment]
Hey, @pauldraper 👋 

Thanks for that example! Yeah, it was really slow -- took 14 minutes to complete for me. I just made a few changes which should speed things up considerably. With those changes, that same example now completes in ~2 minutes for me. 

I just pushed a new version (0.7.0) with these changes, so please try using the latest version and let me know if you're still having problems.

Thanks again!
